### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by guggedse** [ioBroker/ioBroker.corrently#6]
The Link to green Index doesn't work.
The new one is https://corrently.de/api/stromdao/gsi?key=&PLZ=

**Comment by Apollon77** [comment]
hat "green index" you mean?

**Comment by guggedse** [comment]
It's the link/request in main.js to get the green Index json with the  the zip-localisation .
"43    request(`https://api.corrently.io/core/gsi?plz=${adapter.config.PLZ}`, (err, response, body) => {"
change to
"43   request(`https://corrently.de/api/stromdao/gsi?key=&plz=${adapter.config.PLZ}`, (err, response, body) => {"
You may test it in a browser
