### ISSUE TITLE
Adapter doesn't work anymore

### ISSUE THREAD

**Issue by Maverick78de** [ioBroker/ioBroker.corrently#9]
It seems the backend API has changed
The Adapter reports an error during update values

corrently.0 | 2023-02-05 18:26:03.497 | info | Terminated (NO_ERROR): Without reason
corrently.0 | 2023-02-05 18:26:03.384 | error | Invalid answer: {"err":true,"message":"invalid zipcode","input":{}}
corrently.0 | 2023-02-05 18:26:02.707 | info | config PLZ: 06886
corrently.0 | 2023-02-05 18:26:02.673 | info | starting. Version 0.0.2 (non-npm: ioBroker/ioBroker.corrently#bb2bf91ca78207ca5237747b4acb3c85dd4d8908) in /opt/iobroker/node_modules/iobroker.corrently, node: v12.22.12, js-controller: 4.0.24

**Comment by GermanBluefox** [comment]
Thanks for PR!
